In [1]:
import torch
import math
from torch import nn
import torch.nn.functional as F

In [2]:
#Q-function.py
#defining the Q-function 
#Q(s,a) in manuscript

num_chromosome=44
chrom_width=50
max_copy=20
normal_const=1e-5;
single_loci_loss=normal_const*(1-2e-1)
WGD=normal_const*0.6

#switch structure mentioned in section 3.3.4
#kernel sizes for convolution layers
nkernels_switch = [20,40,80]
activatiion_wgd=torch.tanh
class WGD_Net(nn.Module):
    def __init__(self):
        super(WGD_Net, self).__init__()
        #chromosome permutation invariant structure as described in section 3.3.3
        #slide for chromosome is 1 and the filter length in this dimension is also 1
        #thus, the same filter goes through all chromosomes in the same fashion
        self.conv1=nn.Conv2d(1, nkernels_switch[0], (1,3),(1,1),(0,1))
        self.conv2=nn.Conv2d(nkernels_switch[0],nkernels_switch[1] , (1,3),(1,1), (0,1))
        self.conv3=nn.Conv2d(nkernels_switch[1],nkernels_switch[2] , (1,5),(1,1), (0,0))
        self.linear=nn.Linear(nkernels_switch[2],1)
    
    def forward(self, x):
        #y=torch.clamp((F.relu(x.mean(3)-1)-0.5+0.5*F.relu(1-x.mean(3))),-1,1).sum((1,2))
        y=20*(x.mean((1,2,3))-1.5)
        y=y.reshape(x.shape[0],1).detach()
        x=x.reshape(x.shape[0],1,num_chromosome,chrom_width)
        x=F.max_pool2d(activatiion_wgd(self.conv1(x)),(1,5),(1,5),(0,0))
        x=F.max_pool2d(activatiion_wgd(self.conv2(x)),(1,2),(1,2),(0,0))
        x=(activatiion_wgd(self.conv3(x))).sum((2,3))
        x=self.linear(x)
        x=x/2
        #residule representation in x as described in section 3.3.4
        x=y/2+x
        x=torch.sigmoid(x)
        return x

#chromosome evaluation net 
#Used in Chrom_NN (which is Q_{phi_1}(s,c) in section 3.3.1)
#kernel sizes for convolution layers
nkernels_chr = [80,120,160]
activation_cnp=torch.tanh
class CNP_Val(nn.Module):
    def __init__(self):
        super(CNP_Val, self).__init__()
        self.conv1=nn.Conv2d(1, nkernels_chr[0], (1,5),(1,1),(0,2))
        self.conv2=nn.Conv2d(nkernels_chr[0],nkernels_chr[1] , (1,3),(1,1), (0,1))
        self.conv3=nn.Conv2d(nkernels_chr[1],nkernels_chr[2] , (1,3),(1,1), (0,1))
        self.conv4=nn.Conv2d(nkernels_chr[2],1, (1,5),(1,1), (0,0))
    
    def forward(self, x):
        x=F.max_pool2d(activation_cnp(self.conv1(x)),(1,3),(1,3),(0,1))
        x=F.max_pool2d(activation_cnp(self.conv2(x)),(1,2),(1,2),(0,1))
        x=F.max_pool2d(activation_cnp(self.conv3(x)),(1,2),(1,2),(0,1))
        #KL divergence is always nonpositive
        x=0.25+F.elu(self.conv4(x),0.25)
        #number of sample * 44 chromosomes
        x=x.reshape(x.shape[0],num_chromosome)
        return x

#Implemts Q_{phi_1}(s,c) in section 3.3.1
#It combines two chromosome evaluation nets mentioned above,
#with a switch structure in section 3.3.4 to form Q_{phi_1}(s,c)
class Chrom_NN(nn.Module):
    def __init__(self):
        super(Chrom_NN,self).__init__()
        #two parts of the Chrom_NN
        #NN for CNP without WGD 
        self.Val_noWGD=CNP_Val()
        #NN for CNP with WGD
        self.Val_WGD=CNP_Val()
    
    def forward(self,x,sigma):
        #probability for WGD, which is computed by switch structure
        sigma=sigma.expand(-1,num_chromosome)
        #we assume the copy number for each loci ranges from 0~9
        #for samples without WGD
        
        #y represents if a chromosome have abnormal copy numbers (positions with copy number other than 1)
        y=torch.ceil((torch.abs(x-1)).mean(3)/max_copy)
        y=y.reshape(x.shape[0],num_chromosome)
        y=y.detach()
        #Residule representation mentioned in section 3.3.4
        #the value for Q_{phi_1}(s,c) is computed as Val_no (the value estimated by the neural net, the residule part)+ y (the empirial estimation) 
        Val_no=self.Val_noWGD.forward(x)
        #chromosome with all 1 copies don't need any CNV and thus will be less likely mutated.
        Val_no=-(1-y)*math.log(single_loci_loss)*2+((y*Val_no).sum(1)).reshape(x.shape[0],1).expand(-1,num_chromosome)
        #for samples with WGD
        #it is similar to the previsou part, where z is an equivalent for y and Val_wgd is an equivalent for Val_no
        z=torch.ceil((torch.abs(x-2*(x//2))).mean(3)/max_copy)
        z=z.reshape(x.shape[0],num_chromosome)
        z=z.detach()
        Val_wgd=self.Val_WGD.forward(x)
        Val_wgd=-(1-z)*math.log(single_loci_loss)*2+(z*Val_wgd).sum(1).reshape(x.shape[0],1).expand(-1,num_chromosome)-math.log(WGD)
        
        #combine two NN with switch as defined in Section 3.3.4
        x=sigma*Val_wgd+(1-sigma)*Val_no
        x=-x
        return x



#starting point and gain or loss (defined as sp in manuscript) 
#Used in CNV_NN (which is Q_{phi_2}(s,c,sp) on section 3.3.1)
#kernel sizes for convolution layers
nkernels_CNV = [80,120,160,10]
activation_cnv=torch.tanh
class CNV_Val(nn.Module):
    def __init__(self):
        super(CNV_Val,self).__init__()
        self.conv1=nn.Conv2d(1, nkernels_CNV[0], (1,7),(1,1),(0,3))
        self.conv2=nn.Conv2d(nkernels_CNV[0],nkernels_CNV[1] , (1,7),(1,1), (0,3))
        self.conv3=nn.Conv2d(nkernels_CNV[1],nkernels_CNV[2] , (1,7),(1,1), (0,3))
        self.conv4=nn.Conv2d(nkernels_CNV[2], nkernels_CNV[3], (1,7),(1,1), (0,3))
        self.linear=nn.Linear(nkernels_CNV[3]*chrom_width,2*chrom_width-1)
    
    def forward(self,x):
        x=activation_cnv(self.conv1(x))
        x=activation_cnv(self.conv2(x))
        x=activation_cnv(self.conv3(x))
        x=activation_cnv(self.conv4(x))
        x=x.reshape(x.shape[0],nkernels_CNV[3]*chrom_width)
        x=self.linear(x)
        #number of samples* [(50 regions)*(2(gain or loss))-1] 
        #Only have 50*2-1=99 output dimensions because we fix the average these output
        #The average of them could be arbitrary because of the partitioning
        return x

#Implemts Q_{phi_2}(s,c,sp) in section 3.3.1
#It combines two CNV_Val nets mentioned above,
#with a switch structure in section 3.3.4 to form Q_{phi_2}(s,c,sp)
class CNV_NN(nn.Module):
    def __init__(self):
        super(CNV_NN,self).__init__()
        #two network setting
        self.CNV_noWGD=CNV_Val()
        self.CNV_WGD=CNV_Val()
    
    def forward(self,x,sigma):
        #as in section 3.3.4
        #y is the empirical estimation
        #Val_no is the redidule representation
        y=torch.Tensor(x.shape[0],chrom_width,2)
        y[:,:,0]=F.relu(x-1)
        y[:,:,1]=F.relu(1-x)
        y=y.reshape(x.shape[0],2*chrom_width)
        y=y[:,1:(2*chrom_width)]-y[:,0:1].expand(-1,2*chrom_width-1)
        y=-y.detach()*math.log(single_loci_loss)
        Val_no=self.CNV_noWGD.forward(x.reshape(x.shape[0],1,1,chrom_width))
        Val_no=y+Val_no
        
        z=((torch.abs(x-2*(x//2))).reshape(x.shape[0],chrom_width,1)).expand(-1,-1,2)
        z=z.reshape(x.shape[0],2*chrom_width)
        z=z[:,1:(2*chrom_width)]-z[:,0:1].expand(-1,2*chrom_width-1)
        z=-z.detach()*math.log(single_loci_loss)
        Val_wgd=self.CNV_WGD.forward(x.reshape(x.shape[0],1,1,chrom_width))
        Val_wgd=z+Val_wgd
        #switch
        x=sigma*Val_wgd+(1-sigma)*Val_no
        return(x)
    
     
    def find_one_cnv(self,chrom,sigma,last_cnv=-1):
        #used for finding the cnv during deconvolution
        #it is not used in training process
        
        res_cnv=self.forward(chrom,sigma)
        #if there is originally a break point for start
        #rule system 
        break_start=torch.zeros(chrom.shape[0],50,2,requires_grad=False)
        chrom_shift=torch.zeros(chrom.shape[0],50,requires_grad=False)
        chrom_shift[:,1:]=chrom[:,:49]
        #allow adding one copy for every breakpoint
        break_start[:,:,1]=torch.ceil(torch.abs(chrom-chrom_shift)/max_copy)
        #always allow adding one chromosone
        break_start[:,0,1]=1
        #don't allow lose one copy when copy number equalls 1
        break_start[:,:,0]=break_start[:,:,1]
        break_start[:,:,0]=break_start[:,:,0]*torch.ceil((chrom/2-0.5)/max_copy)
        break_start=break_start.reshape(chrom.shape[0],100)
        res_cnv_full=torch.zeros(chrom.shape[0],100)
        res_cnv_full[:,1:]=res_cnv
        
        if last_cnv>0: #not the first step or lossing one chromosome
            forbidden=2*last_cnv//2+(1-last_cnv%2)
            break_start[0][forbidden]=0
        #Prior_rule=break_start
        res_cnv_full=res_cnv_full+torch.log(break_start)
        #best cnv according to the current Q
        cnv_max_val,cnv_max=torch.max(res_cnv_full,1)
        #print(res_cnv_full)
        return int(cnv_max[0])
    


#end point
#Used in End_Point_NN (which is Q_{phi_3}(s,c,sp,ep) on section 3.3.1)
#kernel sizes for convolution layers
nkernels_End = [80,120,240]
activation_end=torch.tanh
class End_Point_Val(nn.Module):
    def __init__(self):
        super(End_Point_Val,self).__init__()
        self.conv1=nn.Conv2d(2, nkernels_End[0], (1,7),(1,1),(0,3))
        self.conv2=nn.Conv2d(nkernels_End[0],nkernels_End[1] , (1,7),(1,1), (0,3))
        self.conv3=nn.Conv2d(nkernels_End[1],nkernels_End[2] , (1,7),(1,1), (0,3))
        self.linear=nn.Linear(nkernels_End[2]*chrom_width,chrom_width-1)
    
    def forward(self,old,new):
        x=torch.Tensor(old.shape[0],2,1,chrom_width)
        x[:,0,0,:]=old
        x[:,1,0,:]=new
        x=x.detach()
        x=activation_end(self.conv1(x))
        x=activation_end(self.conv2(x))
        x=activation_end(self.conv3(x))
        x=x.reshape(x.shape[0],nkernels_End[2]*chrom_width)
        x=self.linear(x)
        #number of samples* [(chrom_width regions)-1] 
        #Only have chrom_width-1=49 output dimensions because we fix the average these output
        #The average of them could be arbitrary because of the partitioning
        return x
    
#Implemts Q_{phi_3}(s,c,sp,ep) in section 3.3.1
#It combines two End_Point_Val nets mentioned above,
#with a switch structure in section 3.3.4 to form Q_{phi_3}(s,c,sp,ep)
class End_Point_NN(nn.Module):
    def __init__(self):
        super(End_Point_NN,self).__init__()
        #two network setting
        self.Val_noWGD=End_Point_Val()
        self.Val_WGD=End_Point_Val()
    
    def forward(self,old,new,sigma):
        
        y=F.relu((old-1)*(old-new))
        y=y[:,1:chrom_width]-y[:,0:1].expand(-1,chrom_width-1)
        y=-y.detach()*math.log(single_loci_loss)
        Val_no=self.Val_noWGD.forward(old,new)
        Val_no=Val_no+y
        
        z=(old-2*(old//2))*(1-(new-2*(new//2)))
        z=z[:,1:chrom_width]-z[:,0:1].expand(-1,chrom_width-1)
        z=-z.detach()*math.log(single_loci_loss)
        Val_wgd=self.Val_WGD.forward(old,new)
        Val_wgd=Val_wgd+z
        #switch
        x=sigma*Val_wgd+(1-sigma)*Val_no
        return x
    
    
    def find_end(self,old,new,sigma,start_loci,cnv,valid):
        #used for finding the end during loading data
        res_end=self.forward(old,new,sigma)
        
        break_end=torch.zeros(old.shape[0],chrom_width,requires_grad=False)
        chrom_shift=torch.zeros(old.shape[0],chrom_width,requires_grad=False)
        chrom_shift[:,:49]=old[:,1:]
        #allow adding one copy for every breakpoint
        break_end[:,:]=torch.ceil(torch.abs(old-chrom_shift)/max_copy)
        #always allow adding one chromosone
        break_end[:,chrom_width-1]=1
        
        for i in range(old.shape[0]):
            #can't end before starting point
            break_end[i,:int(start_loci[i])]=0*break_end[i,:int(start_loci[i])]
            #don't allow lose one copy when copy number equalls 1
            if(cnv[i]<0.5):
                j=int(start_loci[i])+1
                while(j<chrom_width):
                    if(old[i][j]<1.5):
                        break
                    j=j+1
                break_end[i,j:chrom_width]=0*break_end[i,j:chrom_width]
        res_end_full=torch.zeros(old.shape[0],chrom_width)
        res_end_full[:,1:]=res_end
        
        #Prior_rule=break_end
        res_end_full=res_end_full+torch.log(break_end)
        end_max_val,end_max=torch.max(res_end_full,1)
        return end_max+1
    
    
    def find_one_end(self,old,new,sigma,start,cnv):
        #used for finding the end during deconvolution
        res_end=self.forward(old,new,sigma)
        
        break_end=torch.zeros(old.shape[0],chrom_width,requires_grad=False)
        chrom_shift=torch.zeros(old.shape[0],chrom_width,requires_grad=False)
        chrom_shift[:,:chrom_width-1]=old[:,1:]
        #allow adding one copy for every breakpoint
        break_end[:,:]=torch.ceil(torch.abs(old-chrom_shift)/max_copy)
        #always allow adding one chromosone
        break_end[:,chrom_width-1]=1
        #can't end before starting point
        break_end[0,:start]=0*break_end[0,:start]
        #don't allow lose one copy when copy number equalls 1
        if(cnv<0.5):
            j=start+1
            while(j<chrom_width):
                if(old[0][j]<1.5):
                    break
                j=j+1
            break_end[0,j:chrom_width]=0*break_end[0,j:chrom_width]
        res_end_full=torch.zeros(old.shape[0],chrom_width)
        res_end_full[:,1:]=res_end
        #Prior_rule=break_end
        res_end_full=res_end_full+torch.log(break_end)
        end_max_val,end_max=torch.max(res_end_full,1)
        end_max=int(end_max[0])
        return end_max+1
        

#combine all separate networks
#add Rule system

#calculating the softmax
#prevent inf when taking log(exp(x))
#log_exp is always gonna be between 1 and the total number of elements
def Soft_update(val1,soft1,val2,soft2):
    bias=val1.clone()
    log_exp=soft1.clone()
    set1=[torch.ge(val1,val2)]
    bias[set1]=val1[set1]
    log_exp[set1]=soft1[set1]+soft2[set1]*torch.exp(val2[set1]-val1[set1])
    set2=[torch.lt(val1,val2)]
    bias[set2]=val2[set2]
    log_exp[set2]=soft2[set2]+soft1[set2]*torch.exp(val1[set2]-val2[set2])
    return bias,log_exp



#Combine all the separate modules mentioned above
#Implementation of Q(s,a)
class Q_learning(nn.Module):
    def __init__(self):
        super(Q_learning,self).__init__()
        self.switch=WGD_Net()
        #the output refer to Q_{\phi_1}(s,c)
        self.Chrom_model=Chrom_NN()
        #the output refer to Q_{\phi_2}(s,c,sp)
        self.CNV=CNV_NN()
        #the output refer to Q_{\phi_3}(s,sp,c,ep)
        self.End=End_Point_NN()
    
    
    def forward(self,state,next_state,chrom,chrom_new,Chr,cnv,start_loci,end_loci,valid):
        '''
        computing the final advantage(loss) used for training
        loss in Thereom1
        state: s in Q(s,a)
        next_state: s' in softmaxQ(s',a')
        Chr,cnv,end_loci: a in Q(s,a)
        chrom,chrom_new,start_loci,end_loci: intermediate results from s,a, which is preprossed to make computation faster
            e.g. chrom is CNP of the Chr(part of a) from the state(s)
            They could be seen as a mapping without parameters to learn:f(s,a)
        valid: a boolean array, indicating if a training sample is valid (e.g. have non negative copy numbers for all loci)
        '''
        
        #computing softmaxQ(s',a')
        #It is a tradition in RL that gradient does not backpropogate through softmaxQ(s',a'), but only through Q(s,a) to make convergence faster
        #there is no theoritical guarantee behind, and it is only a practical trick
        sigma_next=self.switch(next_state)
        x,y=self.Softmax(next_state,sigma_next)
        x=x+torch.log(y)
        #computing r(s,a)
        x=x+Reward(start_loci,end_loci)
        x=x.detach()
        
        #computing Q(s,a)
        sigma=self.switch.forward(state)
        #Q_{phi_1}(s,c)
        res_chrom=self.Chrom_model.forward(state,sigma)
        
        #Q_{phi_2}(s,c,sp)
        res_cnv=self.CNV.forward(chrom,sigma)
        #if there is originally a break point for start
        #real world constraint as described in section 3.3.2
        #only allow starting points (sp) to be the break points of CNP
        break_start=torch.zeros(state.shape[0],chrom_width,2,requires_grad=False)
        chrom_shift=torch.zeros(state.shape[0],chrom_width,requires_grad=False)
        chrom_shift[:,1:]=chrom[:,:(chrom_width-1)]
        #allow adding one copy for every breakpoint
        break_start[:,:,1]=torch.ceil(torch.abs(chrom-chrom_shift)/max_copy)
        #always allow adding one chromosone
        break_start[:,0,1]=1
        #don't allow lose one copy when copy number equals 0, otherwise there is going to be negative copy numbers
        break_start[:,:,0]=break_start[:,:,1]
        break_start[:,:,0]=break_start[:,:,0]*torch.ceil((chrom/2-0.5)/max_copy)
        break_start=break_start.reshape(state.shape[0],2*chrom_width)
        res_cnv_full=torch.zeros(state.shape[0],2*chrom_width)
        res_cnv_full[:,1:]=res_cnv
        res_cnv_full=res_cnv_full+torch.log(break_start)
        
        #Q_{phi_2}(s,c,sp)-softmax(Q_{phi_2}(s,c,sp)) as described in section 3.3.1
        cnv_max_val,cnv_max=torch.max(res_cnv_full,1)
        cnv_softmax=res_cnv_full-cnv_max_val.reshape(state.shape[0],1).expand(-1,2*chrom_width)
        cnv_softmax=torch.exp(cnv_softmax).sum(1)
        x=x+cnv_max_val+torch.log(cnv_softmax)
        
        #Q_{phi_3}(s,c,sp,ep)
        res_end=self.End.forward(chrom,chrom_new,sigma)
        #if there is originally a break point for end
        #and if this is after the starting point
        #real world constraint in section 3.3.2
        break_end=torch.zeros(state.shape[0],chrom_width,requires_grad=False)
        chrom_shift=torch.zeros(state.shape[0],chrom_width,requires_grad=False)
        chrom_shift[:,:(chrom_width-1)]=chrom[:,1:]
        #allow adding one copy for every breakpoint
        break_end[:,:]=torch.ceil(torch.abs(chrom-chrom_shift)/max_copy)
        #always allow adding one chromosone
        break_end[:,chrom_width-1]=1
        for i in range(state.shape[0]):
            #can't end before starting point
            break_end[i,:int(start_loci[i])]=0*break_end[i,:int(start_loci[i])]
            #don't allow lose one copy when copy number equalls 1
            if(cnv[i]<0.5):
                j=int(start_loci[i])+1
                while(j<chrom_width):
                    if(chrom[i][j]<1.5):
                        break
                    j=j+1
                break_end[i,j:chrom_width]=0*break_end[i,j:chrom_width]
            
        res_end_full=torch.zeros(state.shape[0],chrom_width)
        res_end_full[:,1:]=res_end
        
        #real world constraint described in section 3.3.2
        res_end_full=res_end_full+torch.log(break_end)
        end_max_val,end_max_temp=torch.max(res_end_full,1)
        end_softmax=res_end_full-end_max_val.reshape(state.shape[0],1).expand(-1,chrom_width)
        end_softmax=torch.exp(end_softmax).sum(1)
        #Q_{phi_3}(s,c,sp,ep)-softmax(Q_{phi_3}(s,c,sp,ep)) as described in section 3.3.1
        x=x+end_max_val+torch.log(end_softmax)
        
        for i in range(state.shape[0]):
            if valid[i]>0.5:#check validity to prevent inf-inf which ends in nan
                x[i]=x[i]-res_chrom[i][int(Chr[i])]
                cnv_rank=int(start_loci[i]*2+cnv[i])
                x[i]=x[i]-res_cnv_full[i][cnv_rank]
                end_rank=int(end_loci[i]-1)
                x[i]=x[i]-res_end_full[i][end_rank]
        
        #remove training data which include invalid actions
        x=x*valid
        #return avdantage as well as a best cnv and sigma used for generating training data
        #used for training in the next step
        return x,cnv_max,sigma,res_chrom,res_cnv_full,res_end_full
     
    def Softmax(self,next_state,sigma):
        #compute softmax_{a'} Q(s',a')
        x=self.Chrom_model.forward(next_state,sigma)
        max_chrom=torch.max(x,1)[0]
        softmax_chrom=x-max_chrom.reshape(x.shape[0],1).expand(-1,num_chromosome)
        softmax_chrom=torch.exp(softmax_chrom).sum(1)
        #special action END
        #all the remaining abnormal loci are treated to be caused by several independent single locus copy number changes
        end_val=torch.sum(torch.abs(next_state-1),(1,2,3))*math.log(single_loci_loss)
        max_chrom,softmax_chrom=Soft_update(max_chrom,softmax_chrom,end_val,torch.ones(x.shape[0]))
        #if there is a WGD followed immediately
        for i in range(x.shape[0]):
            #real world constraint as described in section 3.3.2
            #do not allow (reversing) WGD when the CNP contain odd numbers for some loci
            if (not torch.any(next_state[i]-2*torch.floor(next_state[i]/2)>0.5)) and torch.any(next_state[i]>0.5):
                sigma_wgd=self.switch(torch.floor(next_state[i:(i+1)]/2))
                sigma_wgd=sigma_wgd.detach()
                wgd_val,wgd_soft=self.Softmax(torch.floor(next_state[i:(i+1)]/2),sigma_wgd)
                max_chrom[i],softmax_chrom[i]=Soft_update(torch.ones(1)*max_chrom[i],torch.ones(1)*softmax_chrom[i],torch.ones(1)*wgd_val,torch.ones(1)*wgd_soft)
        
        return max_chrom,softmax_chrom
  

#Minimum example
if __name__ == "__main__":
    #test different parts separately
    '''
    switch=WGD_Net()
    Chrom_model=Chrom_NN()
    print(Chrom_model)
    #test the structure of permutation invariant structure
    x=torch.ones(3,1,num_chromosome,50)
    x[0][0][0][0:50]=2
    x[2][0][1][0:50]=2
    prob=switch.forward(x)
    print(prob)
    res=Chrom_model.forward(x,prob)
    print(res)
    res=-float('inf')
    res=torch.LongTensor(3)
    
    print(torch.log(res.type(torch.DoubleTensor)))
    #CNV
    CNV=CNV_NN()
    res=CNV.forward(x[:,0,0,0:50],prob)
    print(CNV)
    print(res.shape)
    #END
    End=End_Point_NN()
    res=End.forward(x[:,0,0,0:50],x[:,0,0,0:50]+1,prob)
    print(End)
    print(res.shape)
    '''
    #test Q-learning
    x=torch.ones(3,1,num_chromosome,50)
    y=torch.ones(3,1,num_chromosome,50)
    x[0][0][0][0:50]=2
    x[2][0][1][0:50]=2
    chrom=x[:,0,0,:]
    chrom_new=y[:,0,0,:]
    Chr=torch.zeros(3)
    cnv=torch.ones(3)
    start_loci=torch.zeros(3)
    end_loci=torch.ones(3)*50
    valid=torch.ones(3)
    Q_model=Q_learning()
    #res,cnv_max,sigma,t,t2,t3=Q_model.forward(x,y,chrom,chrom_new,Chr,cnv,start_loci,end_loci,valid)
    #print(res)
    #print(cnv_max)
    #loss=res.pow(2).mean()
    #print(loss)
    #loss.backward()
    #params = list(Q_model.parameters())
    #print(params[0].grad[0])
    #print(Q_model.switch.conv1.weight[0])

In [78]:
#simulate data for testing
def Simulate_data(batch_size=15,Number_of_step=70):
    state=torch.ones(batch_size,1,num_chromosome,chrom_width,requires_grad=False)
    next_state=torch.ones(batch_size,1,num_chromosome,chrom_width,requires_grad=False)
    Chr=torch.ones(batch_size,requires_grad=False).type(torch.LongTensor)
    step=torch.zeros(batch_size,requires_grad=False)
    wgd=torch.zeros(batch_size,requires_grad=False)
    valid=torch.ones(batch_size,requires_grad=False)
    
    start_loci=torch.randint(high=chrom_width,size=(batch_size,),requires_grad=False)
    end_loci=torch.LongTensor(batch_size)
    cnv=torch.ones(batch_size,requires_grad=False)
    chrom=torch.Tensor(batch_size,chrom_width)
    chrom_new=torch.Tensor(batch_size,chrom_width)
    
    Chr_truth=torch.zeros(batch_size,Number_of_step)
    CNV_truth=torch.zeros(batch_size,Number_of_step)
    End_truth=torch.zeros(batch_size,Number_of_step)
    
    
    step_counter=0
    while(step_counter<Number_of_step):
        for i in range(batch_size):
            #reset valid after they have been checked
            valid[i]=1
            start_loci[i]=torch.randint(high=chrom_width,size=(1,))[0]
            end_loci[i]=1+torch.randint(low=start_loci[i],high=50,size=(1,))[0]
            if torch.rand(1)[0]>0.3:
                Chr[i]=torch.randint(high=num_chromosome,size=(1,))[0]
            #adding probability to sample chromosomal changes during training
            if torch.rand(1)[0]>0.8:
                start_loci[i]=0
                end_loci[i]=chrom_width
            #cnv
            if torch.rand(1)[0]>0.7:
                cnv[i]=0
            #modifying cnp
            prob_wgd=0.1/(1+math.exp(-step[i]+15))
            #wgd          
            if False and (torch.rand(1)[0]<prob_wgd and wgd[i]<1):
                wgd[i]=1
                state[i]=state[i]*2
                next_state[i]=next_state[i]*2
                Chr_truth[i][int(step[i])]=-1
                CNV_truth[i][int(step[i])]=-1
                End_truth[i][int(step[i])]=-1
                step[i]=step[i]+1
                continue
                #adding cnv effect
                #increasing copies when no wgd
                #decreasing copies when wgd
            if wgd[i]>0.5:
                cnv[i]=1-cnv[i]
            state[i][0][Chr[i]][(start_loci[i]):(end_loci[i])]=state[i][0][Chr[i]][(start_loci[i]):(end_loci[i])]-(cnv[i]-0.5)*2
            chrom[i]=state[i][0][Chr[i]][:]
            #reverse effect on chrom_new
            chrom_new[i]=state[i][0][Chr[i]][:]
            chrom_new[i][(start_loci[i]):]=chrom_new[i][(start_loci[i]):]+(cnv[i]-0.5)*2
            #not going to negative values
            if(torch.any(state[i][0][Chr[i]][(start_loci[i]):(end_loci[i])]< -0.5)):
                valid[i]=0
            #not joining breakpoints
            if(start_loci[i]>0.5 and torch.abs(chrom[i][start_loci[i]]-chrom[i][start_loci[i]-1])<0.5):
                valid[i]=0
            if(end_loci[i]<chrom_width-0.5 and torch.abs(chrom[i][end_loci[i]-1]-chrom[i][end_loci[i]])<0.5):
                valid[i]=0
            if valid[i]>0 :
                next_state[i]=state[i].clone()
                Chr_truth[i][int(step[i])]=Chr[i]+1
                CNV_truth[i][int(step[i])]=start_loci[i]*2+cnv[i]+1
                End_truth[i][int(step[i])]=end_loci[i]
                step[i]=step[i]+1
                
            #stay to further train the current step
            #or resample another action
            else:
                state[i]=next_state[i].clone()
        step_counter=step_counter+1
    for i in range(batch_size):
        temp_Chr=Chr_truth.clone()
        temp_CNV=CNV_truth.clone()
        temp_End=End_truth.clone()
        for j in range(int(step[i].item())):
            Chr_truth[i][int(step[i].item())-1-j]=temp_Chr[i][j]
            CNV_truth[i][int(step[i].item())-1-j]=temp_CNV[i][j]
            End_truth[i][int(step[i].item())-1-j]=temp_End[i][j]
    return Chr_truth,CNV_truth,End_truth,state

In [ ]:
#Deconvolution.py
#used for deconvolution of CNP history

def Deconvolute(model,cnp,Chr,CNV,End):
    '''
    Deconvolution samples the maximum action in a greedy way
    model:the trained Q-learning model
    cnp: the input CNP, shape: Number of CNP,1,44 (#Chr),50 (#regions for one chromosome)
    Chr,CNV,END: output tensor,shape: Number of CNP, maximum length of history
    output: for Chr: -1 indicates WGD, 0 indicates no action, 1~44 the chromosome
            for CNV: only valid if Chr is not -1 or 0
                     indicates the starting point (CNV//2) and the type of CNV (CNV%2==1 for gain and CNV%2==0 for loss)
            for End: only valid if Chr is not -1 or 0
                     indicates the end point for a CNV.
    '''
    max_step=int(Chr.shape[1])
    
    for i in range(cnp.shape[0]):
        flag=False
        current_cnp=cnp[i:(i+1)]
        sigma=model.switch(current_cnp)
        if sigma[0]<0.5:
            flag=True
        step=0
        while(step<max_step):
            #it is also possible to manually set the switch if deemed necessary
            sigma=model.switch(current_cnp)
            #hard classification
            if not flag:
                sigma=torch.ceil(sigma)
            #else:
            #    sigma=torch.zeros_like(sigma)
            #print(sigma)
            res_chrom=model.Chrom_model(current_cnp,sigma)
            #print(res_chrom)
            #find the chromosome with the maximum probability
            val,temp_Chr=res_chrom.max(1)
            temp_Chr=int(temp_Chr)
            Chr[i][step]=temp_Chr+1
            #WGD
            if (not torch.any(current_cnp-2*torch.floor(current_cnp/2)>0.5)) and torch.any(current_cnp>0.5):
                sigma_wgd=model.switch(torch.floor(current_cnp/2))
                res_chrom_wgd=model.Chrom_model(torch.floor(current_cnp/2),sigma_wgd)
                val_wgd,temp=res_chrom_wgd.max(1)
                if not flag:#val_wgd>=val and not flag:
                    val=val_wgd
                    Chr[i][step]=-1
                    CNV[i][step]=-1
                    End[i][step]=-1
                    flag=True
            #special action END
            val_end=torch.sum(torch.abs(current_cnp-1))*math.log(single_loci_loss)
            if val_end>=val:
                val=val_end
                Chr[i][step]=0
                #print(val_end)
                break
            #if WGD
            if Chr[i][step]< -0.5:
                current_cnp=(current_cnp/2).floor()
                flag=True
            #if not WGD or END
            elif Chr[i][step]>0.5:
                #find best CNV
                chrom=current_cnp[:,0,temp_Chr,:]
                last_step=-1
                if step>1 and Chr[i][step]==Chr[i][step-1]:
                    last_step=int(CNV[i][step-1].item())
                CNV[i][step]=model.CNV.find_one_cnv(chrom,sigma,last_step)
                cnv_temp=int(CNV[i][step]%2)
                start_temp=int(CNV[i][step]//2)
                #find best End
                chrom_new=chrom.clone()
                chrom_new[:,start_temp:]=chrom_new[:,start_temp:]+(cnv_temp-0.5)*2
                End[i][step]=model.End.find_one_end(chrom,chrom_new,sigma,start_temp,cnv_temp)
                #updata cnp
                #print(chrom)
                #print(start_temp,End[i][step],cnv_temp)
                
                current_cnp[:,0,temp_Chr,start_temp:int(End[i][step])]=current_cnp[:,0,temp_Chr,start_temp:int(End[i][step])]+(cnv_temp-0.5)*2
                
            step=step+1
    return Chr,CNV,End,current_cnp
    




if __name__=="__main__":
    #model = Q_learning()
    #model.load_state_dict(torch.load("/data/suzaku/ted/HOME/model"))
    #model.eval()
    counter_global=torch.randint(10000,(1,))[0]
    #loading simulated data
    num_step=50
    Chr_truth,CNV_truth,End_truth,state=Simulate_data(batch_size=1,Number_of_step=num_step)
    Chr=torch.zeros(state.shape[0],num_step*2)
    CNV=torch.zeros(state.shape[0],num_step*2)
    End=torch.zeros(state.shape[0],num_step*2)
    state_copy=state.clone()
    #deconvolution
    Chr,CNV,End,state=Deconvolute(model,state,Chr,CNV,End)
    CNV[Chr>0.5]=CNV[Chr>0.5]+1
    print(Chr,Chr_truth)
    #check if the model picks the correct chromosome
    print(CNV,CNV_truth)
    print(End,End_truth)

In [49]:
#torch.save(model.state_dict(),"/data/suzaku/ted/HOME/model_tanh")

In [73]:
def Heur1(cnp,Chr,CNV,End):
    max_step=int(Chr.shape[1])
    
    for i in range(cnp.shape[0]):
        current_cnp=cnp[i:(i+1)]
        current_locus=0
        step=0
        while(step<max_step and current_locus<num_chromosome*chrom_width):
            current_Chr=current_locus//chrom_width
            current_start=current_locus%chrom_width
            if current_cnp[0][0][current_Chr][current_start]==1:
                current_locus+=1
                continue
            elif current_cnp[0][0][current_Chr][current_start]<1:
                current_cnv=1
            else:
                current_cnv=-1
            current_end=current_start
            while(current_end<50):
                if current_cnp[0][0][current_Chr][current_end]!=current_cnp[0][0][current_Chr][current_start]:
                    break
                current_end+=1
            current_cnp[0,0,current_Chr,current_start:current_end]+=current_cnv
            Chr[i][step]=current_Chr+1
            CNV[i][step]=2*current_start+(current_cnv+1)//2+1
            End[i][step]=current_end
            step=step+1
    return Chr,CNV,End,current_cnp

if __name__=="__main__":
    #loading simulated data
    num_step=50
    Chr_truth,CNV_truth,End_truth,state=Simulate_data(batch_size=1,Number_of_step=num_step)
    Chr=torch.zeros(state.shape[0],num_step*2)
    CNV=torch.zeros(state.shape[0],num_step*2)
    End=torch.zeros(state.shape[0],num_step*2)
    state_copy=state.clone()
    #deconvolution
    Chr,CNV,End,state=Heur1(state,Chr,CNV,End)
    print(Chr,Chr_truth)
    #check if the model picks the correct chromosome
    print(CNV,CNV_truth)
    print(End,End_truth)

tensor([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  2.,  2.,  2.,
          3.,  3.,  3.,  4.,  4.,  4.,  5.,  5.,  5.,  5.,  6.,  6.,  7.,  7.,
          7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,
          7.,  7.,  7.,  8.,  8.,  8.,  8.,  9.,  9.,  9., 10., 10., 10., 10.,
         11., 11., 11., 12., 12., 12., 12., 12., 12., 12., 12., 12., 12., 12.,
         12., 12., 12., 12., 12., 12., 12., 12., 13., 14., 15., 16., 16., 16.,
         17., 17., 17., 17., 17., 17., 17., 17., 18., 19., 20., 20., 21., 22.,
         23., 24.]]) tensor([[43., 43., 43., 17., 12.,  1.,  1.,  4., 20., 40., 38.,  3., 17., 19.,
          6., -1., 17.,  7., 43., 17.,  8.,  7., 11., 36., 12., 10., 31., 16.,
         12., 31., 29., 30.,  2., 29., 34.,  7.,  9., 37., 29., 12.,  5., 35.,
         39., 41.,  7.,  1., 37., 31., 43., 30.]])
tensor([[ 1.,  5.,  5., 29., 29., 29., 29., 79., 79., 79., 79.,  1.,  1.,  1.,
          1., 57., 57.,  1., 17., 17.,  1., 65., 65., 65., 

In [56]:
def Heur2(cnp,Chr,CNV,End):
    max_step=int(Chr.shape[1])
    
    for i in range(cnp.shape[0]):
        current_cnp=cnp[i:(i+1)]
        current_locus=0
        step=0
        flag=False
        if current_cnp.mean()<1.7:
            flag=True
        while(step<max_step and ((not flag) or current_locus<num_chromosome*chrom_width)):
            if current_locus==num_chromosome*chrom_width:
                flag=True
                current_locus=0
                current_cnp//=2
                Chr[i][step]=-1
                CNV[i][step]=-1
                End[i][step]=-1
                step+=1
                continue
            current_Chr=current_locus//chrom_width
            base_line=2
            if flag:
                base_line=1
            if current_cnp[0][0][current_Chr].mean()>base_line*(1.5):
                current_cnp[0][0][current_Chr]-=1
                Chr[i][step]=current_Chr+1
                CNV[i][step]=1
                End[i][step]=50
                current_locus=current_Chr*chrom_width
                step+=1
                continue
            elif current_cnp[0][0][current_Chr].mean()<base_line*(0.5):
                current_cnp[0][0][current_Chr]+=1
                Chr[i][step]=current_Chr+1
                CNV[i][step]=2
                End[i][step]=50
                current_locus=current_Chr*chrom_width
                step+=1
                continue
            current_start=current_locus%chrom_width
            if (flag and current_cnp[0][0][current_Chr][current_start]==1) or ((not flag) and current_cnp[0][0][current_Chr][current_start]%2==0):
                current_locus+=1
                continue
            elif current_cnp[0][0][current_Chr][current_start]<base_line:
                current_cnv=1
            else:
                current_cnv=-1
            current_end=current_start
            while(current_end<50):
                if current_cnp[0][0][current_Chr][current_end]!=current_cnp[0][0][current_Chr][current_start]:
                    break
                current_end+=1
            current_cnp[0,0,current_Chr,current_start:current_end]+=current_cnv
            Chr[i][step]=current_Chr+1
            CNV[i][step]=2*current_start+(current_cnv+1)//2+1
            End[i][step]=current_end
            step=step+1
    return Chr,CNV,End,current_cnp

if __name__=="__main__":
    #loading simulated data
    num_step=50
    Chr_truth,CNV_truth,End_truth,state=Simulate_data(batch_size=1,Number_of_step=num_step)
    Chr=torch.zeros(state.shape[0],num_step*2)
    CNV=torch.zeros(state.shape[0],num_step*2)
    End=torch.zeros(state.shape[0],num_step*2)
    #deconvolution
    Chr,CNV,End,state=Heur2(state,Chr,CNV,End)
    print((state-1).abs().sum())
    print(Chr)
    #check if the model picks the correct chromosome
    print(CNV)
    print(End)

tensor(0.)
tensor([[ 3.,  3.,  6.,  6., 10., 10., 10., 10., 12., 12., 12., 15., 15., 15.,
         15., 18., 18., 21., 21., 21., 21., 26., 26., 26., 27., 27., 28., 28.,
         28., 28., 28., 32., 32., 32., 32., 34., 34., 35., 35., 35., 37., 40.,
         40., 40., 41., 44., -1.,  3.,  6.,  8., 10., 12., 15., 17., 20., 22.,
         24., 28., 35., 35., 36., 39., 42., 43., 44.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.],
        [ 2.,  2.,  6.,  7.,  9.,  9., 10., 11., 17., 17., 17., 17., 18., 18.,
         19., 20., 20., 20., 20., 21., 22., 22., 22., 22., 23., 24., 24., 25.,
         25., 26., 26., 26., 26., 26., 26., 27., 27., 31., 32., 36., 40., 42.,
         42., 43., 44., 44., 44., 44., 44., 44., -1.,  9., 12., 13., 16., 17.,
         17., 17., 18., 20., 21., 22., 22., 22., 22., 25., 44.,  0.,  0.,  0.,
          0.,  0.,  0

In [ ]:
import pandas as pd
dirc="/data/suzaku/ted/HOME/noWGD"
num_step=50

Chr_truth,CNV_truth,End_truth,state=Simulate_data(batch_size=50,Number_of_step=num_step)
pd.DataFrame(Chr_truth.numpy()).astype(int).to_csv(dirc+"Chr_truth.csv",header=False,index=False)
pd.DataFrame(CNV_truth.numpy()).astype(int).to_csv(dirc+"CNV_truth.csv",header=False,index=False)
pd.DataFrame(End_truth.numpy()).astype(int).to_csv(dirc+"End_truth.csv",header=False,index=False)

Chr=torch.zeros(state.shape[0],num_step*2)
CNV=torch.zeros(state.shape[0],num_step*2)
End=torch.zeros(state.shape[0],num_step*2)
state_copy=state.clone()
Chr,CNV,End,state=Heur1(state,Chr,CNV,End)

pd.DataFrame(Chr.numpy()).astype(int).to_csv(dirc+"Chr_Heur1.csv",header=False,index=False)
pd.DataFrame(CNV.numpy()).astype(int).to_csv(dirc+"CNV_Heur1.csv",header=False,index=False)
pd.DataFrame(End.numpy()).astype(int).to_csv(dirc+"End_Heur1.csv",header=False,index=False)

state=state_copy.clone()
Chr=torch.zeros(state.shape[0],num_step*2)
CNV=torch.zeros(state.shape[0],num_step*2)
End=torch.zeros(state.shape[0],num_step*2)
Chr,CNV,End,state=Heur2(state,Chr,CNV,End)

pd.DataFrame(Chr.numpy()).astype(int).to_csv(dirc+"Chr_Heur2.csv",header=False,index=False)
pd.DataFrame(CNV.numpy()).astype(int).to_csv(dirc+"CNV_Heur2.csv",header=False,index=False)
pd.DataFrame(End.numpy()).astype(int).to_csv(dirc+"End_Heur2.csv",header=False,index=False)

state=state_copy.clone()
Chr=torch.zeros(state.shape[0],num_step*2)
CNV=torch.zeros(state.shape[0],num_step*2)
End=torch.zeros(state.shape[0],num_step*2)
Chr,CNV,End,state=Deconvolute(model,state,Chr,CNV,End)
CNV[Chr>0.5]=CNV[Chr>0.5]+1
pd.DataFrame(Chr.numpy()).astype(int).to_csv(dirc+"Chr_RL.csv",header=False,index=False)
pd.DataFrame(CNV.numpy()).astype(int).to_csv(dirc+"CNV_RL.csv",header=False,index=False)
pd.DataFrame(End.numpy()).astype(int).to_csv(dirc+"End_RL.csv",header=False,index=False)

In [17]:
state=torch.ones(1,1,num_chromosome,50)
state[0][0][:((num_chromosome//2)+0),:]=2
state[0][0][((num_chromosome//2)+0):,:]=2
model.switch.forward(state)

tensor([[0.9621]], grad_fn=<SigmoidBackward>)

In [9]:
model.switch.forward(state)

tensor([[0.0021]], grad_fn=<SigmoidBackward>)

In [10]:
(state).mean(3)

tensor([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
          1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
          1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]])

In [1207]:
state[0][0][32]

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [1208]:
model.Chrom_model(state,model.switch.forward(state))[0][32]

tensor(-21.5296, grad_fn=<SelectBackward>)

tensor([[0.2000, 0.2000, 0.2000, 0.2000, 0.2000],
        [0.2000, 0.2000, 0.2000, 0.2000, 0.2000],
        [0.2000, 0.2000, 0.2000, 0.2000, 0.2000]])

In [1284]:
state[0][0][:22]=torch.Tensor(major[:,1]).view((22,50))
state[0][0][22:]=torch.Tensor(minor[:,1]).view((22,50))
model.switch.forward(state)

tensor([[0.0589]], grad_fn=<SigmoidBackward>)

In [11]:
import pandas as pd
import numpy as np

In [12]:
major=np.loadtxt("/data/suzaku/ted/WGD/major_Kuramoch_comp_samp.txt")
minor=np.loadtxt("/data/suzaku/ted/WGD/minor_Kuramoch_comp_samp.txt")
major.shape

(1100, 2)

In [36]:
state[0][0][:22]=torch.Tensor(major[:,0]).view((22,50))
state[0][0][22:]=torch.Tensor(minor[:,0]).view((22,50))
Chr=torch.zeros(state.shape[0],200)
CNV=torch.zeros(state.shape[0],200)
End=torch.zeros(state.shape[0],200)
state_copy=state.clone()
#deconvolution
Chr,CNV,End,state=Deconvolute(model,state,Chr,CNV,End)
print(Chr)
#check if the model picks the correct chromosome
print(CNV)
print(End)
print(torch.nonzero(Chr))

tensor([[ 1.,  2.,  4.,  5.,  6.,  6.,  6.,  6.,  8.,  8.,  8.,  8.,  8.,  9.,
         10., 10., 10., 11., 12., 12., 12., 13., 13., 14., 15., 16., 16., 17.,
         17., 18., 19., 19., 20., 20., 21., 21., 21., 23., 24., 25., 25., 26.,
         27., 27., 27., 28., 28., 28., 29., 30., 31., 32., 32., 33., 34., 35.,
         36., 36., 37., 38., 38., 39., 40., 41., 41., 42., 43., 43., -1.,  1.,
          1.,  5.,  6.,  6.,  6.,  6.,  7.,  8.,  8.,  8.,  8., 10., 12., 13.,
         13., 14., 14., 14., 16., 17., 17., 19., 19., 20., 21., 21., 21., 21.,
         21., 21., 21., 23., 23., 25., 25., 27., 28., 28., 29., 29., 30., 32.,
         32., 32., 33., 35., 35., 36., 36., 36., 36., 37., 39., 39., 40., 41.,
         43., 44.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.

In [37]:
state[0][0][:22]=torch.Tensor(major[:,1]).view((22,50))
state[0][0][22:]=torch.Tensor(minor[:,1]).view((22,50))
Chr=torch.zeros(state.shape[0],200)
CNV=torch.zeros(state.shape[0],200)
End=torch.zeros(state.shape[0],200)
state_copy=state.clone()
#deconvolution
Chr,CNV,End,state=Deconvolute(model,state,Chr,CNV,End)
print(Chr)
#check if the model picks the correct chromosome
print(CNV)
print(End)
print(torch.nonzero(Chr))

tensor([[ 1.,  1.,  1.,  2.,  4.,  5.,  6.,  6.,  6.,  6.,  8.,  8.,  8.,  8.,
          9., 10., 10., 11., 12., 12., 12., 15., 16., 16., 17., 17., 18., 19.,
         19., 20., 20., 20., 21., 21., 23., 23., 23., 24., 25., 25., 26., 27.,
         27., 28., 28., 28., 28., 29., 31., 32., 33., 34., 35., 36., 37., 38.,
         38., 40., 41., 41., 42., 43., 43., -1.,  1.,  1.,  1.,  1.,  1.,  5.,
          6.,  6.,  6.,  6.,  7.,  7.,  8.,  8.,  8., 10., 12., 13., 14., 14.,
         16., 17., 17., 17., 19., 20., 21., 21., 21., 21., 21., 23., 25., 25.,
         27., 28., 28., 28., 28., 28., 29., 29., 30., 33., 35., 36., 36., 37.,
         39., 39., 40., 41., 44.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.

In [ ]:
state[0][0][:22]=torch.Tensor(major[:,1]).view((22,50))
state[0][0][22:]=torch.Tensor(minor[:,1]).view((22,50))
model.switch(state)

##### 